services:
  _defaults:
    public: true
  
  prestashop.adapter.order.command_handler.issue_partial_refund_handler:
    class: WHStopEmailCreditSlip\Adapter\Order\CommandHandler\IssuePartialRefundHandler
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.order.refund.order_refund_calculator'
      - '@prestashop.adapter.order.refund.order_slip_creator'
      - '@prestashop.adapter.order.refund.voucher_generator'
      - '@prestashop.adapter.order.refund.updater'
      - '@prestashop.adapter.context_state_manager'
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Order\Command\IssuePartialRefundCommand
        
  prestashop.adapter.order.command_handler.issue_standard_refund_handler:
    class: WHStopEmailCreditSlip\Adapter\Order\CommandHandler\IssueStandardRefundHandler
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.order.refund.order_refund_calculator'
      - '@prestashop.adapter.order.refund.order_slip_creator'
      - '@prestashop.adapter.order.refund.voucher_generator'
      - '@prestashop.adapter.order.refund.updater'
      - '@prestashop.adapter.context_state_manager'
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Order\Command\IssueStandardRefundCommand
        
  prestashop.adapter.order.command_handler.issue_return_product_handler:
    class: WHStopEmailCreditSlip\Adapter\Order\CommandHandler\IssueReturnProductHandler
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.order.refund.order_refund_calculator'
      - '@prestashop.adapter.order.refund.order_slip_creator'
      - '@prestashop.adapter.order.refund.voucher_generator'
      - '@prestashop.adapter.order.refund.updater'
      - '@prestashop.adapter.context_state_manager'
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Order\Command\IssueReturnProductCommand
  
  prestashop.adapter.order.refund.order_slip_creator:
    class: WHStopEmailCreditSlip\Adapter\Order\Refund\OrderSlipCreator
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@translator'